[pytest]
# Маркеры тестов
markers =
    ui: UI тесты
    api: API тесты
    smoke: Дымовые тесты
    regression: Регрессионные тесты

# Настройки отчетов
addopts =
    -v
    --alluredir=allure-results
    --strict-markers
    -p no:cacheprovider

# Пути
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*